plugins {
	id "se.bjurr.gradle.bundle-command-shadow" version "2.2.1"
}

dependencies {
	implementation "se.bjurr.violations:violation-comments-to-bitbucket-cloud-lib:2.2.0"
	implementation "se.bjurr.violations:violations-lib:2.1.0"
	implementation 'info.picocli:picocli:4.7.7'
	implementation "org.slf4j:slf4j-simple:2.0.19"
}

shadowExtension {
	mainClass.set("se.bjurr.violations.main.Main")
	relocate.set("org:org,jakarta:jakarta,javax:javax,com:com,se:se,io:io")
}

staticCodeAnalysisExtension {
	maxViolations.set(0)
}

javaExtension {
	javaVersion = 17
}
